# Generated by Django 3.2.9 on 2021-11-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ingredient', models.CharField(max_length=50)),
                ('quantite_ingredient', models.IntegerField()),
                ('id_recette', models.IntegerField()),
            ],
        ),
    ]
