# Generated by Django 3.2.9 on 2021-11-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0002_alter_recette_auteur_recette'),
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='id_recette',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recette',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recette.recette'),
            preserve_default=False,
        ),
    ]
